"""NotebookLM's audio: Customise opened, chosen and generated by the page.

The owner's 09-30 run spent 10 computer-use steps here. Our code looked for a
separate "Customise Audio Overview" arrow that no longer exists, and the
computer-use prompt forbade the one thing that now opens Customise: the Studio's
"Audio Overview" tile. Capture 5 (tests/fixtures/notebooklm_0930/) shows the
window the tile opens: Format as four radio rows, Length as Short / Default /
Long toggles (none for Brief), and "Generate later" / "Generate now".

Every test here runs Phase 3's real audio step, `run_phase3_audio`, against a
local page built from that capture, in headless Chrome. Nothing opens a real
website. Computer use is replaced by a recorder, so "no computer use" is a
measurement, not a promise.
"""
from __future__ import annotations

import asyncio
import json
import re
from pathlib import Path
from types import SimpleNamespace

import pytest

import prompts
import research

FIX = Path(__file__).parent / "fixtures" / "notebooklm_0930"
NB_URL = "https://notebooklm.google.com/notebook/nb-0930"


@pytest.fixture(scope="module")
def chrome():
    try:
        from patchright.async_api import async_playwright
    except Exception as e:                                    # pragma: no cover
        pytest.skip(f"patchright unavailable: {e}")
    loop = asyncio.new_event_loop()

    async def _start():
        pw = await async_playwright().start()
        try:
            b = await pw.chromium.launch(channel="chrome", headless=True)
        except Exception:
            await pw.stop()
            raise
        return pw, b, await b.new_context(viewport={"width": 1280, "height": 760})

    try:
        pw, b, ctx = loop.run_until_complete(_start())
    except Exception as e:                                    # pragma: no cover
        loop.close()
        pytest.skip(f"system Chrome unavailable: {e}")
    yield SimpleNamespace(run=loop.run_until_complete, ctx=ctx)
    loop.run_until_complete(b.close())
    loop.run_until_complete(pw.stop())
    loop.close()


def _fixture_html(start="Deep dive", stuck="", dead=False, slow_ms=0) -> str:
    src = (FIX / "customise.html").read_text(encoding="utf-8")
    body = 'data-start-format="Deep dive"'
    assert src.count(body) == 1, "the fixture's <body> switches moved"
    extra = f'data-start-format="{start}"'
    if stuck:
        extra += f' data-length-stuck="{stuck}"'
    if dead:
        extra += ' data-generate-dead="1"'
    if slow_ms:
        extra += f' data-generate-slow="{int(slow_ms)}"'
    return src.replace(body, extra)


class _QuickAsyncio:
    """The step's own sleeps (5 s settles, 5 s verify rounds) cut to 20 ms.
    Every wait the page code does is measured on the real clock, so the page's
    own timers still have to fire before a read can pass."""

    def __getattr__(self, name):
        return getattr(asyncio, name)

    @staticmethod
    async def sleep(secs=0, *a, **k):
        await asyncio.sleep(min(float(secs or 0), 0.02))


class _Controls:
    skipped_agents: set = set()

    async def interruptible_sleep(self, *a, **k):
        return "stop"          # end the step at the 2-minute wait after Generate

    def is_stop(self):
        return False

    def is_pause(self):
        return False


def _run_audio(chrome, monkeypatch, length, **switches):
    """Run the audio step on the fixture. Returns (presses on the page,
    computer-use calls, log lines)."""
    lines, cua = [], []

    async def _cua(page, **k):
        cua.append(k)
        return {"text": "generating"}

    async def _false(*a, **k):
        return False

    async def _true(*a, **k):
        return True

    async def _none(*a, **k):
        return None

    monkeypatch.setattr(research, "log", lambda m, lv="INFO", *a, **k: lines.append((lv, str(m))))
    monkeypatch.setattr(research, "emit_event", lambda *a, **k: None)
    monkeypatch.setattr(research, "asyncio", _QuickAsyncio())
    monkeypatch.setattr(research, "_controls", _Controls())
    monkeypatch.setattr(research, "_work_tab_signed_out", _false)
    monkeypatch.setattr(research, "check_hv_gate", _true)
    monkeypatch.setattr(research, "start_narration_ticker", lambda *a, **k: (None, None))
    monkeypatch.setattr(research, "stop_narration_ticker", _none)
    monkeypatch.setattr(research, "_observe_dom_success", lambda *a, **k: None)
    monkeypatch.setattr(research, "_dump_nlm_audio_dom", _none)
    monkeypatch.setattr(research, "_shadow_observed_cua", _cua)

    page = chrome.run(chrome.ctx.new_page())
    try:
        chrome.run(page.set_content(_fixture_html(**switches)))

        async def _url():
            return NB_URL

        browser = SimpleNamespace(page=page, current_url=_url)
        out = chrome.run(research.run_phase3_audio.__wrapped__(
            browser, object(), NB_URL, None, podcast_length=length))
        presses = json.loads(chrome.run(page.evaluate("() => document.body.dataset.log || '[]'")))
    finally:
        chrome.run(page.close())
    assert out == {"audio_path": None}, out      # stopped at the 2-minute wait
    return presses, cua, [m for _, m in lines]


# ═════════════════════════════════════════════════════════════════════════════
# The configured length → Format + Length, chosen, read back, generated
# ═════════════════════════════════════════════════════════════════════════════

def test_long_is_deep_dive_and_long_all_by_the_page(chrome, monkeypatch):
    """The default. Customise opens on Deep dive + Default (capture frame 4):
    the page presses the tile, Long, then Generate now — nothing else."""
    presses, cua, lines = _run_audio(chrome, monkeypatch, "long")
    assert presses == ["tile", "length:Long", "generate-now:Deep dive|Long"], (presses, lines)
    assert cua == [], f"computer use ran {len(cua)} time(s): {[c.get('current_step') for c in cua]}"
    assert any('Audio started by the page: Deep dive + Long read back as chosen, '
               'then "Generate now" pressed' in m for m in lines), lines


def test_short_is_brief_with_no_length(chrome, monkeypatch):
    """Brief has no Length row (capture frame 7); nothing waits for one."""
    presses, cua, lines = _run_audio(chrome, monkeypatch, "short")
    assert presses == ["tile", "format:Brief", "generate-now:Brief|-"], (presses, lines)
    assert cua == []


def test_default_is_deep_dive_and_default(chrome, monkeypatch):
    presses, cua, lines = _run_audio(chrome, monkeypatch, "default")
    assert presses == ["tile", "generate-now:Deep dive|Default"], (presses, lines)
    assert cua == []


def test_a_window_on_another_format_moves_to_deep_dive_first(chrome, monkeypatch):
    """ASSUMED start state: the window opening on Critique, whose Length row has
    no Long (capture frame 10). Deep dive must be chosen first, and Long only
    once the redrawn Length row offers it."""
    presses, cua, lines = _run_audio(chrome, monkeypatch, "long", start="Critique")
    assert presses == ["tile", "format:Deep dive", "length:Long",
                       "generate-now:Deep dive|Long"], (presses, lines)
    assert cua == []


# ═════════════════════════════════════════════════════════════════════════════
# The read-back decides; computer use gets the SAME open window
# ═════════════════════════════════════════════════════════════════════════════

def _one_panel_open_handover(cua):
    assert len(cua) == 1, [c.get("current_step") for c in cua]
    assert cua[0]["current_step"] == "configure_generate_audio_panel_open", cua[0]["current_step"]
    assert "ALREADY DONE FOR YOU" in cua[0]["mission_prompt"]


def test_a_length_that_does_not_read_back_is_never_generated_by_the_page(chrome, monkeypatch):
    """Long is pressed but stays unchosen: the page must not press Generate now
    on Default, and computer use takes the open window instead."""
    presses, cua, lines = _run_audio(chrome, monkeypatch, "long", stuck="Long")
    assert presses == ["tile", "length:Long"], (presses, lines)
    _one_panel_open_handover(cua)
    assert any("The page could not finish Customise (length reads Default after "
               "choosing Long)" in m for m in lines), lines


# ═════════════════════════════════════════════════════════════════════════════
# "Generate now" is pressed once, ever: a press that landed is never repeated
# ═════════════════════════════════════════════════════════════════════════════

def test_a_generate_now_that_leaves_the_window_open_is_never_pressed_again(chrome, monkeypatch):
    """The press landed but the window stays open and nothing shows as
    generating. The page cannot tell a press that failed from a slow one that
    took, and a second press on one that took makes a second audio that cannot
    be deleted. So computer use is not handed a Generate mission: the step goes
    on to the checks and the poll, which watch for the audio."""
    monkeypatch.setattr(research, "_NLM_GENERATE_WATCH_S", 1.0, raising=False)
    presses, cua, lines = _run_audio(chrome, monkeypatch, "long", dead=True)
    assert presses == ["tile", "length:Long", "generate-now:Deep dive|Long"], (presses, lines)
    assert cua == [], ("computer use was handed the window after the page's own "
                       f"Generate now: {[c.get('current_step') for c in cua]}")
    assert any('"Generate now" was pressed once' in m and "not pressing it again" in m
               for m in lines), lines
    assert any("Post-generate inventory" in m for m in lines), lines


def test_a_slow_server_reply_is_waited_for_not_handed_on(chrome, monkeypatch):
    """ASSUMED timing: Generate now takes, but the window closes and "Generating
    Audio Overview…" shows only after 9 s. The page is still watching then, so
    it reads as started by the page."""
    presses, cua, lines = _run_audio(chrome, monkeypatch, "long", slow_ms=9000)
    assert presses == ["tile", "length:Long", "generate-now:Deep dive|Long"], (presses, lines)
    assert cua == [], [c.get("current_step") for c in cua]
    assert any('Audio started by the page: Deep dive + Long read back as chosen, '
               'then "Generate now" pressed' in m for m in lines), lines


# ═════════════════════════════════════════════════════════════════════════════
# The computer-use fallback may click the tile
# ═════════════════════════════════════════════════════════════════════════════

def _section(text, start, end):
    a = text.index(start)
    return text[a:text.index(end, a)]


@pytest.mark.parametrize("length", ["short", "default", "long"])
def test_the_computer_use_fallback_opens_customise_from_the_tile(length):
    p = prompts.make_prompt_audio_generate(length)
    allowed = _section(p, "You may ONLY click:", "Steps (")
    never = _section(p, "CRITICAL — NEVER CLICK THESE", "You may ONLY click:")
    assert re.search(r'The "Audio Overview" tile .*ONCE', allowed), allowed
    assert '"Generate now"' in allowed and "Generate later" not in allowed, allowed
    assert "card body" not in never.lower() and "gear" not in p.lower(), never
    assert '"Generate later"' in never, never
    step3 = _section(p, "\n3. ", "\n4. ")
    assert 'click the "Audio Overview" tile in the Studio panel ONCE' in step3, step3
    step6 = _section(p, "\n6. ", "\n7. ")
    assert 'Click "Generate now" (never "Generate later") EXACTLY ONCE' in step6, step6


def test_the_vision_hints_say_the_tile_too():
    hint = research._HOTSPOT_VISION_HINTS["p3-audio-customize"]["context_hint"]
    assert "'Audio Overview' tile" in hint and "gear" not in hint, hint
    gen = research._HOTSPOT_VISION_HINTS["audio-generate"]["context_hint"]
    assert "'Generate now'" in gen and "gear" not in gen, gen


# ═════════════════════════════════════════════════════════════════════════════
# The fixture is the capture
# ═════════════════════════════════════════════════════════════════════════════

def _walk(n):
    yield n
    for k in n.get("k") or []:
        yield from _walk(k)


def _capture():
    return json.loads((FIX / "customise-capture.json").read_text(encoding="utf-8"))


def _captured_window(frame):
    """(format rows' labels, [(length, aria-checked)], action buttons) of one
    captured frame."""
    nodes = [n for m in frame["menus"] for n in _walk(m)]
    rows = [n["label"] for n in nodes if n["tag"] == "LABEL"
            and "mdc-form-field" in n["a"].get("class", "")]
    lengths = [(n["label"], n["a"]["aria-checked"]) for n in nodes
               if n["tag"] == "BUTTON" and n["a"].get("role") == "radio"]
    actions = [n["label"] for n in nodes if n["tag"] == "BUTTON"
               and (n.get("label") or "").startswith("Generate")]
    return rows, lengths, actions


_FIXTURE_WINDOW_JS = r"""() => {
    const norm = (s) => (s || '').replace(/\s+/g, ' ').trim();
    const d = document.querySelector('mat-dialog-container[role="dialog"]');
    if (!d) return null;
    return {
        title: norm(d.querySelector('h2').textContent),
        rows: Array.from(d.querySelectorAll(
            'mat-radio-group[role="radiogroup"][aria-labelledby="showFormat-label"] label.mdc-form-field'))
            .map((l) => norm(l.textContent).slice(0, 40)),
        lengths: Array.from(d.querySelectorAll(
            'mat-button-toggle-group[role="radiogroup"][aria-labelledby="episodeLength-label"] button[role="radio"]'))
            .map((b) => [norm(b.textContent), b.getAttribute('aria-checked')]),
        actions: Array.from(d.querySelectorAll('button'))
            .map((b) => norm(b.textContent)).filter((t) => t.startsWith('Generate')),
    };
}"""


def test_the_fixture_is_the_capture(chrome):
    """The local page shows what capture 5 showed: the tile, and the window on
    Deep dive (frame 4), after Brief (frame 7) and after Critique (frame 10)."""
    cap = {f["index"]: f for f in _capture()["frames"]}
    tile = next(n for p in cap[2]["panels"] for n in _walk(p)
                if n["a"].get("aria-label") == "Audio Overview")
    assert tile["tag"] == "DIV" and tile["a"]["role"] == "button", tile
    assert cap[3]["clicked"][3]["a"]["aria-label"] == "Audio Overview"   # the tile opened it
    page = chrome.run(chrome.ctx.new_page())
    try:
        chrome.run(page.set_content(_fixture_html()))
        got_tile = chrome.run(page.evaluate(
            "() => { const t = document.querySelector('basic-create-artifact-button "
            "[aria-label=\"Audio Overview\"]'); return [t.tagName, t.getAttribute('role')]; }"))
        assert got_tile == ["DIV", "button"], got_tile
        chrome.run(page.click('[aria-label="Audio Overview"]'))
        chrome.run(page.wait_for_selector('mat-dialog-container[role="dialog"]'))
        for idx, choose in ((4, None), (7, "Brief"), (10, "Critique")):
            if choose:
                chrome.run(page.click(f'mat-radio-button:has-text("{choose}") label'))
                chrome.run(page.wait_for_timeout(400))
            got = chrome.run(page.evaluate(_FIXTURE_WINDOW_JS))
            rows, lengths, actions = _captured_window(cap[idx])
            assert got["title"] == "Customise Audio Overview"
            assert got["rows"] == rows, (idx, got["rows"], rows)
            assert [tuple(x) for x in got["lengths"]] == lengths, (idx, got["lengths"], lengths)
            assert got["actions"] == actions == ["Generate later", "Generate now"], (idx, got["actions"])
    finally:
        chrome.run(page.close())
