"""Keep the host bridge up across logon — the engine behind `agent resurrect` /
`agent retire`.

On Windows the always-up bridge is a **Scheduled Task** (`SuperAgentBridge`) that
launches the bridge WINDOWLESS (pythonw.exe — no console) at logon, so a reboot
brings it back. `resurrect` also starts it immediately (detached) so it's up
without waiting for the next login. The account session + device selection
persist (keyring + prefs), so a restart resumes cleanly without re-login.

schtasks `/TR` can't set a working directory, and embedding the launch code
inline trips schtasks' quote parsing, so we drop a tiny launcher script in the
store dir (~/.super-agent/) that puts the agent package on sys.path and calls the
`serve` entry point. The Scheduled Task then runs ``pythonw <launcher>`` — the
same proven quoted-path shape the backend supervisor uses.

The schtasks argv + launcher source are built by pure functions (unit-testable);
only install / uninstall / status / start_detached shell out, and only on
Windows.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from . import config

TASK_NAME = "SuperAgentBridge"


def is_windows() -> bool:
    return sys.platform.startswith("win")


def agent_dir() -> Path:
    """The dir that contains the ``facade`` package (so ``import facade`` works
    even when the Scheduled Task launches with cwd = C:\\Windows\\System32)."""
    return Path(__file__).resolve().parent.parent


def pythonw_exe() -> str:
    """No-console interpreter (pythonw.exe) sibling of the current interpreter,
    falling back to sys.executable. Mirrors research.py _supervisor_python_exe so
    the bridge never pops a visible console window at logon."""
    cur = Path(sys.executable)
    if cur.name.lower() == "python.exe":
        sib = cur.parent / "pythonw.exe"
        if sib.exists():
            return str(sib)
    return str(cur)


def launcher_path() -> Path:
    """The generated launcher script the Scheduled Task / detached start run."""
    return config.store_dir() / "bridge_launcher.py"


def launcher_source(agentdir: Path | None = None) -> str:
    """Python source for the launcher: inject the agent dir on sys.path, then
    call the `serve` entry point. ``repr`` quotes the path safely (handles the
    backslashes in a Windows path), so there are no schtasks-quoting hazards."""
    d = str(agentdir or agent_dir())
    return (
        "# Auto-generated by `agent resurrect` — launches the Super Agent bridge.\n"
        "# Safe to delete; `agent retire` removes it.\n"
        "import sys\n"
        f"sys.path.insert(0, {d!r})\n"
        "from facade.cli import main\n"
        "raise SystemExit(main(['serve']))\n"
    )


def write_launcher(agentdir: Path | None = None) -> Path:
    """Write (refresh) the launcher script; return its path."""
    p = launcher_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(launcher_source(agentdir), encoding="utf-8")
    return p


def run_command(exe: str | None = None, launcher: Path | None = None) -> str:
    """The /TR command line: ``"pythonw.exe" "<launcher>"`` (both quoted)."""
    return f'"{exe or pythonw_exe()}" "{launcher or launcher_path()}"'


def install_argv(task_name: str = TASK_NAME, command: str | None = None) -> list[str]:
    # ONLOGON so it starts at sign-in; LIMITED run level (no elevation needed);
    # /F overwrites an existing task (idempotent re-install).
    # /IT (interactive token) is LOAD-BEARING, not cosmetic: without it schtasks
    # creates an S4U (Service-for-User) task whose logon token cannot decrypt the
    # per-user DPAPI Credential Locker — so keyring.get_password() returns nothing
    # and the rehydrated bridge would come up unauthenticated after a reboot,
    # breaking this file's "resumes cleanly without re-login" promise. The backend
    # SuperResearchBackend task carries /IT for the same reason. pythonw.exe keeps
    # it windowless regardless of /IT.
    return ["schtasks", "/Create", "/TN", task_name, "/TR", command or run_command(),
            "/SC", "ONLOGON", "/RL", "LIMITED", "/IT", "/F"]


def uninstall_argv(task_name: str = TASK_NAME) -> list[str]:
    return ["schtasks", "/Delete", "/TN", task_name, "/F"]


def status_argv(task_name: str = TASK_NAME) -> list[str]:
    return ["schtasks", "/Query", "/TN", task_name]


def _exec(argv: list[str]) -> tuple[bool, str]:
    no_window = getattr(subprocess, "CREATE_NO_WINDOW", 0x08000000) if is_windows() else 0
    try:
        proc = subprocess.run(argv, capture_output=True, text=True, encoding="utf-8",
                              errors="replace", timeout=30, creationflags=no_window)
    except (OSError, subprocess.SubprocessError) as e:  # pragma: no cover - env-specific
        return False, str(e)
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode == 0, out.strip()


def install(task_name: str = TASK_NAME) -> tuple[bool, str]:
    """Pin the bridge to logon (writes the launcher + creates the Scheduled Task)."""
    if not is_windows():
        return False, "autostart is Windows-only for now (use your OS service manager)"
    write_launcher()
    return _exec(install_argv(task_name))


def uninstall(task_name: str = TASK_NAME) -> tuple[bool, str]:
    """Remove the Scheduled Task + the generated launcher (best-effort)."""
    if not is_windows():
        return False, "autostart is Windows-only for now"
    ok, out = _exec(uninstall_argv(task_name))
    try:
        launcher_path().unlink(missing_ok=True)
    except OSError:
        pass
    return ok, out


def status(task_name: str = TASK_NAME) -> tuple[bool, str]:
    if not is_windows():
        return False, "autostart is Windows-only for now"
    return _exec(status_argv(task_name))


def is_installed(task_name: str = TASK_NAME) -> bool:
    """Whether the logon Scheduled Task currently exists (False off-Windows)."""
    ok, _ = status(task_name)
    return ok


def start_detached(exe: str | None = None, launcher: Path | None = None) -> tuple[bool, str]:
    """Start the bridge NOW — windowless + detached, so it survives this process.

    Mirrors research.py's detached daemon-loop spawn (DETACHED_PROCESS |
    CREATE_NEW_PROCESS_GROUP | CREATE_NO_WINDOW, all stdio → DEVNULL)."""
    if not is_windows():
        return False, "windowless background start is Windows-only for now"
    exe = exe or pythonw_exe()
    p = launcher or write_launcher()
    detached = getattr(subprocess, "DETACHED_PROCESS", 0x00000008)
    newgroup = getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0x00000200)
    no_window = getattr(subprocess, "CREATE_NO_WINDOW", 0x08000000)
    try:
        subprocess.Popen(
            [exe, str(p)],
            creationflags=detached | newgroup | no_window,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL, close_fds=True,
        )
    except (OSError, ValueError) as e:  # pragma: no cover - env-specific
        return False, str(e)
    return True, ""
