"""Keep the host bridge up across logon — the engine behind `agent resurrect` /
`agent retire`. Cross-platform, one install/uninstall/status/start_detached API
dispatched by OS:

  • Windows — a **Scheduled Task** (`SuperAgentBridge`) that launches the bridge
    WINDOWLESS (pythonw.exe) at logon. The proven, shipping path.
  • Linux   — a **systemd --user** service (`super-agent-bridge.service`).
  • macOS   — a **launchd LaunchAgent** (`io.superresearch.agent-bridge`).

All three launch the SAME tiny generated launcher (~/.super-agent/bridge_launcher.py)
which puts the agent package on sys.path and calls the `serve` entry point, so the
bridge resumes cleanly after a reboot (the account session + device selection persist
in keyring + prefs).

The per-OS argv / unit / plist are built by pure functions (unit-testable); only
install / uninstall / status / start_detached shell out.

NOTE: the Windows path is the validated one. The Linux (systemd) and macOS (launchd)
paths are unit-tested at the generation + dispatch level but have NOT yet been
validated end-to-end on a live Linux/macOS host.
"""

from __future__ import annotations

import json
import logging
import os
import subprocess
import sys
import time
import urllib.request
from pathlib import Path

from . import config

log = logging.getLogger(__name__)

TASK_NAME = "SuperAgentBridge"                    # Windows Scheduled Task name
SYSTEMD_UNIT = "super-agent-bridge.service"       # Linux systemd --user unit
LAUNCHD_LABEL = "io.superresearch.agent-bridge"   # macOS launchd LaunchAgent label


# ── platform ───────────────────────────────────────────────────────────────────

def is_windows() -> bool:
    return sys.platform.startswith("win")


def is_macos() -> bool:
    return sys.platform == "darwin"


def is_linux() -> bool:
    return sys.platform.startswith("linux")


def platform_label() -> str:
    if is_windows():
        return "Windows"
    if is_macos():
        return "macOS"
    if is_linux():
        return "Linux"
    return sys.platform


# ── shared launcher (every OS runs this) ─────────────────────────────────────

def agent_dir() -> Path:
    """The dir that contains the ``facade`` package (so ``import facade`` works
    even when the service launches with a cwd like C:\\Windows\\System32 or /)."""
    return Path(__file__).resolve().parent.parent


def pythonw_exe() -> str:
    """No-console interpreter (pythonw.exe) sibling of the current interpreter on
    Windows; sys.executable elsewhere (POSIX has no windowless variant — the
    service manager detaches it)."""
    cur = Path(sys.executable)
    if cur.name.lower() == "python.exe":
        sib = cur.parent / "pythonw.exe"
        if sib.exists():
            return str(sib)
    return str(cur)


def launcher_path() -> Path:
    """The generated launcher script the service / detached start run."""
    return config.store_dir() / "bridge_launcher.py"


def launcher_source(agentdir: Path | None = None) -> str:
    """Python source for the launcher: inject the agent dir on sys.path, then call
    the `serve` entry point. ``repr`` quotes the path safely (handles Windows
    backslashes), so there are no schtasks-quoting hazards."""
    d = str(agentdir or agent_dir())
    return (
        "# Auto-generated by `agent resurrect` — launches the Super Agent bridge.\n"
        "# Safe to delete; `agent retire` removes it.\n"
        "import sys\n"
        f"sys.path.insert(0, {d!r})\n"
        "from facade.cli import main\n"
        "raise SystemExit(main(['serve']))\n"
    )


def write_launcher(agentdir: Path | None = None) -> Path:
    """Write (refresh) the launcher script; return its path."""
    p = launcher_path()
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(launcher_source(agentdir), encoding="utf-8")
    return p


def _rm_launcher() -> None:
    try:
        launcher_path().unlink(missing_ok=True)
    except OSError:
        pass


def _exec(argv: list[str]) -> tuple[bool, str]:
    no_window = getattr(subprocess, "CREATE_NO_WINDOW", 0x08000000) if is_windows() else 0
    try:
        proc = subprocess.run(argv, capture_output=True, text=True, encoding="utf-8",
                              errors="replace", timeout=30, creationflags=no_window)
    except (OSError, subprocess.SubprocessError) as e:  # pragma: no cover - env-specific
        return False, str(e)
    out = (proc.stdout or "") + (proc.stderr or "")
    return proc.returncode == 0, out.strip()


# ── talking to the live bridge ────────────────────────────────────────────────
# A restart has to cycle whatever process HOLDS THE PORT, which is often not the
# thing the service manager launched (on Windows, connect/resurrect start the
# bridge with a detached Popen). These probes reach that process directly.
#
# Stdlib only, deliberately: this module's sole local import is `config` (it runs
# from a generated launcher and from the service manager), so it must not need
# `requests`, and importing `bridge` here would be both heavy and circular-ish.


def _healthz(timeout: float = 2.0) -> dict | None:
    """The live bridge's ``/healthz`` body, or None when nothing there is ours.

    Marker-checked (``{"ok": true, "version": …}``) for exactly the reason
    ``cli._bridge_up`` and ``bridge._port_holder_is_bridge`` are: a foreign server
    squatting the port must never read as the bridge — whatever this says yes to
    is what we go on to POST ``/shutdown`` at."""
    try:
        with urllib.request.urlopen(config.bridge_origin() + "/healthz", timeout=timeout) as r:
            body = json.loads(r.read().decode("utf-8", "ignore"))
    except Exception:  # noqa: BLE001 - any transport/parse failure means "not our bridge"
        return None
    if isinstance(body, dict) and body.get("ok") is True and "version" in body:
        return body
    return None


def _post_shutdown(timeout: float = 10.0) -> None:
    """Ask the live bridge to stop — the same call `agent retire` makes.

    Best-effort: connection-refused just means it is already gone, and the bridge
    may well die mid-response (it answers 200, then stops serving on a thread).
    The method MUST be an explicit POST — a bare ``urlopen(url)`` sends GET, which
    ``/shutdown`` answers 404, and every restart would then sit out the stop
    timeout waiting for a bridge nobody asked to stop."""
    req = urllib.request.Request(
        config.bridge_origin() + "/shutdown", data=b"{}", method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        urllib.request.urlopen(req, timeout=timeout).close()
    except Exception:  # noqa: BLE001 - already down, or it died answering; both fine
        pass


def _wait_gone(timeout: float) -> bool:
    """True once nothing answers ``/healthz``, plus a grace for the OS to release
    the loopback socket — mirroring the self-update waiter's own exit poll +
    2s port grace. Deliberately NOT a ``bind()`` probe: Windows SO_REUSEADDR
    semantics make a successful bind an ambiguous signal."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if _healthz() is None:
            time.sleep(2)
            return True
        time.sleep(0.5)
    return False


def _wait_healthz(timeout: float) -> dict | None:
    """The ``/healthz`` body of a bridge that comes up within ``timeout``, else
    None. A launch that was merely *attempted* leaves nothing here."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        body = _healthz()
        if body is not None:
            return body
        time.sleep(0.5)
    return None


# ── Windows: Scheduled Task (validated) ──────────────────────────────────────

def run_command(exe: str | None = None, launcher: Path | None = None) -> str:
    """The /TR command line: ``"pythonw.exe" "<launcher>"`` (both quoted)."""
    return f'"{exe or pythonw_exe()}" "{launcher or launcher_path()}"'


def install_argv(task_name: str = TASK_NAME, command: str | None = None) -> list[str]:
    # ONLOGON so it starts at sign-in; LIMITED run level (no elevation); /F
    # overwrites (idempotent re-install). /IT (interactive token) is LOAD-BEARING:
    # without it schtasks makes an S4U task whose logon token cannot decrypt the
    # per-user DPAPI Credential Locker — keyring.get_password() returns nothing and
    # the rehydrated bridge comes up unauthenticated after a reboot, breaking the
    # "resumes cleanly without re-login" promise. pythonw.exe stays windowless
    # regardless of /IT.
    return ["schtasks", "/Create", "/TN", task_name, "/TR", command or run_command(),
            "/SC", "ONLOGON", "/RL", "LIMITED", "/IT", "/F"]


def uninstall_argv(task_name: str = TASK_NAME) -> list[str]:
    return ["schtasks", "/Delete", "/TN", task_name, "/F"]


def status_argv(task_name: str = TASK_NAME) -> list[str]:
    return ["schtasks", "/Query", "/TN", task_name]


def _win_start(exe: str | None = None, launcher: Path | None = None) -> tuple[bool, str]:
    """Start the bridge NOW — windowless + detached, so it survives this process.
    Mirrors research.py's detached daemon-loop spawn."""
    exe = exe or pythonw_exe()
    p = launcher or write_launcher()
    detached = getattr(subprocess, "DETACHED_PROCESS", 0x00000008)
    newgroup = getattr(subprocess, "CREATE_NEW_PROCESS_GROUP", 0x00000200)
    no_window = getattr(subprocess, "CREATE_NO_WINDOW", 0x08000000)
    try:
        subprocess.Popen(
            [exe, str(p)],
            creationflags=detached | newgroup | no_window,
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL, close_fds=True,
        )
    except (OSError, ValueError) as e:  # pragma: no cover - env-specific
        return False, str(e)
    return True, ""


_STOP_WAIT_SECONDS = 45.0   # for the old bridge to let go of the port
_START_WAIT_SECONDS = 45.0   # for a new one to answer /healthz


def _win_restart(task_name: str = TASK_NAME) -> tuple[bool, str]:
    """Cycle the bridge onto the code on disk, and only claim success if it did.

    Stops the LISTENER rather than the scheduled-task instance. The bridge that is
    actually running is usually NOT one the scheduler launched — `agent connect`
    and `agent resurrect` both start it with a detached Popen (`_win_start`), which
    Task Scheduler has no handle on — so `schtasks /End` has nothing to end. And
    `/Run` exits 0 for merely ATTEMPTING a launch. Together those two reported a
    confident success while the very same process kept serving the very same code.

    The wait between stop and start is load-bearing: a second instance started
    while the old one still owns the port finds it taken, recognises the holder as
    a bridge and returns (``bridge.serve``) — leaving the OLD code serving with
    /Run's exit code still saying 0.
    """
    before = _healthz()

    # Refresh the launcher BEFORE stopping anything: the agent dir moves on a pipx
    # upgrade, which is precisely when a restart gets called, and doing it here
    # means an unwritable store dir aborts with the old bridge still serving.
    try:
        write_launcher()
    except OSError as e:
        return False, f"couldn't refresh the bridge launcher: {e}"

    # A scheduler-launched instance, if there happens to be one. Still best-effort
    # (an idle task legitimately returns non-zero) but no longer the only stop
    # path, so its failures are now diagnosable rather than merely swallowed.
    ended_ok, ended_out = _exec(["schtasks", "/End", "/TN", task_name])
    if not ended_ok:
        log.debug("schtasks /End: %s", ended_out)

    # Only ask the holder to stop once we have PROVEN it is our bridge — a blind
    # POST would fire /shutdown at whatever unrelated local service owns the port.
    if before is not None:
        _post_shutdown()
        if not _wait_gone(_STOP_WAIT_SECONDS):
            return False, f"the bridge on port {config.BRIDGE_PORT} did not stop"

    ok, out = _exec(["schtasks", "/Run", "/TN", task_name])
    if not ok:
        return False, out or "schtasks /Run failed"

    after = _wait_healthz(_START_WAIT_SECONDS)
    if after is None:
        # /IT tasks need an interactive session, and the scheduler can decline for
        # reasons it doesn't report. Fall back to the detached start that
        # connect/resurrect already depend on, rather than leaving the host with no
        # bridge at all.
        started, serr = _win_start()
        if started:
            after = _wait_healthz(_START_WAIT_SECONDS)
        if after is None:
            return False, f"restart issued but no bridge came back ({serr or 'no listener'})"

    # Same version is NOT a failure — restarting onto identical code is legitimate
    # (a config change, an operator cycling it) — but it's worth a log line, since
    # after an upgrade it means the new build isn't what came back.
    if before and before.get("version") == after.get("version"):
        log.info("bridge restarted; version unchanged (%s)", after.get("version"))
    return True, "restarted"


# ── Linux: systemd --user service ─────────────────────────────────────────────

def systemd_unit_path() -> Path:
    return Path.home() / ".config" / "systemd" / "user" / SYSTEMD_UNIT


def systemd_unit_source(exe: str | None = None, launcher: Path | None = None) -> str:
    """The `systemd --user` unit text.

    `Environment=XDG_RUNTIME_DIR` is load-bearing for SELF-UPDATE, not cosmetic.
    ``selfupdate._cgroup_escape_prefix()`` only emits its `systemd-run --user`
    wrapper when a user bus looks reachable, and a unit's environment is not the
    login shell's. Without the escape the update waiter stays in this unit's
    cgroup and systemd's default KillMode=control-group reaps it the instant the
    bridge exits — exactly the documented failure (an empty self-update.log and a
    bridge stuck on the old version). The user manager normally exports this
    variable to its own units already; stating it makes the dependency explicit
    and covers a host where it isn't propagated. `%U` is the unit owner's numeric
    uid, expanded by systemd, and /run/user/$UID is systemd's own default. If a
    host puts the runtime dir elsewhere, the escape degrades to a plain detached
    child rather than failing (see the isdir guard in _cgroup_escape_prefix).
    """
    e = exe or sys.executable
    p = str(launcher or launcher_path())
    return (
        "[Unit]\n"
        "Description=Super Agent bridge (Super Research)\n"
        "After=network-online.target\n"
        "\n"
        "[Service]\n"
        "Type=simple\n"
        f'ExecStart="{e}" "{p}"\n'  # quoted — systemd splits on spaces otherwise
        'Environment="XDG_RUNTIME_DIR=/run/user/%U"\n'
        "Restart=always\n"
        "RestartSec=5\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def systemctl_argv(*verbs: str) -> list[str]:
    return ["systemctl", "--user", *verbs]


def _write_systemd_unit() -> Path:
    write_launcher()
    up = systemd_unit_path()
    up.parent.mkdir(parents=True, exist_ok=True)
    up.write_text(systemd_unit_source(), encoding="utf-8")
    return up


def _linux_install() -> tuple[bool, str]:
    _write_systemd_unit()
    ok, out = _exec(systemctl_argv("daemon-reload"))
    if not ok:
        return ok, out
    return _exec(systemctl_argv("enable", SYSTEMD_UNIT))


def _linux_uninstall() -> tuple[bool, str]:
    ok, out = _exec(systemctl_argv("disable", "--now", SYSTEMD_UNIT))
    try:
        systemd_unit_path().unlink(missing_ok=True)
    except OSError:
        pass
    _rm_launcher()
    if not ok:
        return ok, out
    # disable succeeded → the result that matters now is daemon-reload; surface its
    # failure (with its own message) rather than swallowing it.
    return _exec(systemctl_argv("daemon-reload"))


def _linux_status() -> tuple[bool, str]:
    return _exec(systemctl_argv("is-enabled", SYSTEMD_UNIT))


def _linux_start() -> tuple[bool, str]:
    return _exec(systemctl_argv("start", SYSTEMD_UNIT))


def _linux_restart() -> tuple[bool, str]:
    # `restart` cycles the running unit onto the code on disk. `start` is a NO-OP
    # when the unit is already running (Restart=always keeps it up), so it would
    # keep serving the OLD build after a pipx upgrade.
    return _exec(systemctl_argv("restart", SYSTEMD_UNIT))


# ── macOS: launchd LaunchAgent ───────────────────────────────────────────────

def launchd_plist_path() -> Path:
    return Path.home() / "Library" / "LaunchAgents" / f"{LAUNCHD_LABEL}.plist"


def _xml_escape(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def launchd_plist_source(exe: str | None = None, launcher: Path | None = None) -> str:
    e = _xml_escape(exe or sys.executable)
    p = _xml_escape(str(launcher or launcher_path()))
    return (
        '<?xml version="1.0" encoding="UTF-8"?>\n'
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd">\n'
        '<plist version="1.0">\n'
        '<dict>\n'
        f'  <key>Label</key><string>{LAUNCHD_LABEL}</string>\n'
        '  <key>ProgramArguments</key>\n'
        '  <array>\n'
        f'    <string>{e}</string>\n'
        f'    <string>{p}</string>\n'
        '  </array>\n'
        '  <key>RunAtLoad</key><true/>\n'
        '  <key>KeepAlive</key><true/>\n'
        '</dict>\n'
        '</plist>\n'
    )


def launchctl_argv(*verbs: str) -> list[str]:
    return ["launchctl", *verbs]


def _darwin_install() -> tuple[bool, str]:
    write_launcher()
    pl = launchd_plist_path()
    pl.parent.mkdir(parents=True, exist_ok=True)
    pl.write_text(launchd_plist_source(), encoding="utf-8")
    return _exec(launchctl_argv("load", "-w", str(pl)))


def _darwin_uninstall() -> tuple[bool, str]:
    pl = launchd_plist_path()
    ok, out = _exec(launchctl_argv("unload", "-w", str(pl)))
    try:
        pl.unlink(missing_ok=True)
    except OSError:
        pass
    _rm_launcher()
    return ok, out


def _darwin_status() -> tuple[bool, str]:
    return _exec(launchctl_argv("list", LAUNCHD_LABEL))


def _darwin_start() -> tuple[bool, str]:
    return _exec(launchctl_argv("start", LAUNCHD_LABEL))


def _darwin_restart() -> tuple[bool, str]:
    # `kickstart -k` kills then restarts the loaded job in one atomic step, so the
    # bridge re-execs the code on disk. `launchctl start` alone doesn't cycle a
    # KeepAlive job that's already up (it stays on the OLD build after an upgrade).
    label = f"gui/{os.getuid()}/{LAUNCHD_LABEL}"
    return _exec(launchctl_argv("kickstart", "-k", label))


# ── dispatch (public API) ─────────────────────────────────────────────────────

def _unsupported() -> tuple[bool, str]:
    return (False, f"run-on-startup isn't supported on this platform ({sys.platform})")


def supported() -> bool:
    """Whether run-on-startup pinning is implemented for this OS."""
    return is_windows() or is_linux() or is_macos()


def kind_label() -> str:
    """What the login-pin is on this OS (for user-facing copy)."""
    if is_windows():
        return "Scheduled Task"
    if is_linux():
        return "systemd --user service"
    if is_macos():
        return "launchd LaunchAgent"
    return "service"


def install(task_name: str = TASK_NAME) -> tuple[bool, str]:
    """Pin the bridge to start on login — Windows Scheduled Task / Linux systemd
    --user / macOS launchd. (``task_name`` only affects the Windows task name.)"""
    if is_windows():
        write_launcher()
        return _exec(install_argv(task_name))
    if is_linux():
        return _linux_install()
    if is_macos():
        return _darwin_install()
    return _unsupported()


def uninstall(task_name: str = TASK_NAME) -> tuple[bool, str]:
    """Remove the login pin + the generated launcher (best-effort)."""
    if is_windows():
        ok, out = _exec(uninstall_argv(task_name))
        _rm_launcher()
        return ok, out
    if is_linux():
        return _linux_uninstall()
    if is_macos():
        return _darwin_uninstall()
    return _unsupported()


def status(task_name: str = TASK_NAME) -> tuple[bool, str]:
    if is_windows():
        return _exec(status_argv(task_name))
    if is_linux():
        return _linux_status()
    if is_macos():
        return _darwin_status()
    return _unsupported()


def is_installed(task_name: str = TASK_NAME) -> bool:
    """Whether the login pin currently exists (False on an unsupported OS)."""
    return status(task_name)[0]


def start_detached(exe: str | None = None, launcher: Path | None = None) -> tuple[bool, str]:
    """Start the bridge NOW in the background (windowless on Windows; via the
    service manager on Linux/macOS)."""
    if is_windows():
        return _win_start(exe, launcher)
    if is_linux():
        return _linux_start()
    if is_macos():
        return _darwin_start()
    return _unsupported()


def restart(task_name: str = TASK_NAME) -> tuple[bool, str]:
    """Restart the ALREADY-PINNED background bridge so it re-execs the code on
    disk — the post-update step. A pipx upgrade replaces the package, but the
    running bridge keeps the OLD code in memory until it is cycled, and
    `start_detached` alone can't do it: `systemctl start` / `launchctl start` are
    no-ops on an already-running unit. Mirrors the backend's `_restart_supervisor`
    (whose Windows branch still has the `/End`+`/Run` defect fixed here — see
    `_win_restart`).

    Refuses (False, "not installed") when nothing is pinned. Never raises. On
    Windows it now returns False rather than reporting a success it can't back up:
    `_win_restart` confirms a bridge is actually listening afterwards."""
    if not is_installed(task_name):
        return False, "not installed"
    if is_windows():
        return _win_restart(task_name)
    if is_linux():
        return _linux_restart()
    if is_macos():
        return _darwin_restart()
    return _unsupported()
